/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cursoemvideo.atividadenove;

/**
 *
 * @author mathe
 */
public class Equacao extends javax.swing.JFrame {

    /**
     * Creates new form Equacao
     */
    public Equacao() {
        initComponents();
        painelVal.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRes = new javax.swing.JLabel();
        spnA = new javax.swing.JSpinner();
        spnB = new javax.swing.JSpinner();
        spnC = new javax.swing.JSpinner();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCal = new javax.swing.JButton();
        painelVal = new javax.swing.JPanel();
        lbl11 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lblDelta = new javax.swing.JLabel();
        lblRaizes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>x<sup>2</sup>+</html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 53, 29));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("x+");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 26, 30));

        lblRes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRes.setText("= 0");
        getContentPane().add(lblRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 30, 30));

        spnA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spnA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnAStateChanged(evt);
            }
        });
        getContentPane().add(spnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        spnB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spnB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnBStateChanged(evt);
            }
        });
        getContentPane().add(spnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        spnC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spnC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCStateChanged(evt);
            }
        });
        getContentPane().add(spnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 60, -1));

        lblA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblA.setText("a");
        getContentPane().add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 112, -1, 46));

        lblB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblB.setText("b");
        getContentPane().add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 119, -1, -1));

        lblC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblC.setText("c");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 119, 17, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html>&Delta=</html>");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 119, 42, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html><sup>2</sup>-4.</html>");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 105, 62, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(".");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 119, 4, -1));

        btnCal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCal.setText("<html>Calcular &Delta</html>");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });
        getContentPane().add(btnCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        lbl11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl11.setText("<html>Valor de &Delta</html>");

        lbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl.setText("Tipos de Raízes");

        lblDelta.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDelta.setForeground(new java.awt.Color(0, 0, 255));
        lblDelta.setText("0");

        lblRaizes.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblRaizes.setForeground(new java.awt.Color(0, 0, 255));
        lblRaizes.setText("0");

        javax.swing.GroupLayout painelValLayout = new javax.swing.GroupLayout(painelVal);
        painelVal.setLayout(painelValLayout);
        painelValLayout.setHorizontalGroup(
            painelValLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelValLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelValLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelValLayout.createSequentialGroup()
                        .addComponent(lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                        .addComponent(lblRaizes))
                    .addGroup(painelValLayout.createSequentialGroup()
                        .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDelta)))
                .addContainerGap())
        );
        painelValLayout.setVerticalGroup(
            painelValLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelValLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(painelValLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDelta)
                    .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(painelValLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRaizes))
                .addGap(33, 33, 33))
        );

        getContentPane().add(painelVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 350, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spnAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnAStateChanged
        // TODO add your handling code here:
        lblA.setText(spnA.getValue().toString());
    }//GEN-LAST:event_spnAStateChanged

    private void spnBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnBStateChanged
        // TODO add your handling code here:
        lblB.setText(spnB.getValue().toString());
    }//GEN-LAST:event_spnBStateChanged

    private void spnCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCStateChanged
        // TODO add your handling code here:
        lblC.setText(spnC.getValue().toString());
    }//GEN-LAST:event_spnCStateChanged

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(spnA.getValue().toString());
        int b = Integer.parseInt(spnB.getValue().toString());
        int c = Integer.parseInt(spnC.getValue().toString());
        
        double d = Math.pow(b,2) - 4 * a * c;
        lblDelta.setText(String.format ("%.1f", d));
        
        if (d < 0) {
            lblRaizes.setText("Não existem Raízes Reais");
        } else {
            lblRaizes.setText("Existem Raízes Reais");
        }
        
        
        painelVal.setVisible(true);
    }//GEN-LAST:event_btnCalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblDelta;
    private javax.swing.JLabel lblRaizes;
    private javax.swing.JLabel lblRes;
    private javax.swing.JPanel painelVal;
    private javax.swing.JSpinner spnA;
    private javax.swing.JSpinner spnB;
    private javax.swing.JSpinner spnC;
    // End of variables declaration//GEN-END:variables
}
